package telran.seder.dto;

public enum SederReturneCode {
	OK, 
	MODEL_EXIST,
	CUPBOARD_EXIST,


	PHOTO_EXIST, QUARTES_EXIST,
	ROOM_EXIST, SHELF_EXIST, THIND_EXIST,
	SHELF_FUUL,  CUPBOARD_FOOL, CUPBOARD_NOT_FOOL,
	 NO_CUPBOARD,  NO_PHOTO,
	NO_QUARTES, NO_ROOM, NO_SHELF, NO_THINGS,
	THING_ON_THE_PLACE, THING_IS_WRONG, CUPBOARD_IS_WRONG,
	WRONG_NAME_OF_QUARTES,
	SHELF_NOT_FUUL,
	SIZE_EXIST, OWNER_EXIST, SEAZON_EXIST,
	THING_OR_MODEL_WRONG,
	USER_IS_EXIST,
	PHOTO_DELITED, THING_ALREADY_ON_THE_SHELF,
	NO_ROOM_TO,
	NO_ROOM_FROM,
}
